fix MacOS compile error due to QJasonArray reference value
The compilation on MacOS stops with the following compile error:

/Users/fritz/searchwing/qgroundcontrol/src/Vehicle/Actuators/Actuators.cc:431:26: error: loop variable 'parameterJson' is always a copy because the range of type 'QJsonArray' does not return a reference [-Werror,-Wrange-loop-analysis]
        for (const auto& parameterJson : parameters) {